import { registerStrings } from '../../shared/i18n/index.jsx';

/** Treasure Hunt text (the lobby card strings live in `casino/strings.js`). */
const strings = {
  en: {
    'hunt.title': 'Treasure Hunt',
    'hunt.tagline': 'Dig. Collect. Bank it!',
    'hunt.rules.1': 'On your turn, open tiles one at a time. Gems go into your pot.',
    'hunt.rules.2': 'Open a trapdoor and you lose your pot — and your turn!',
    'hunt.rules.3': 'Bank at any time to keep your pot. Then it is the next player’s turn.',
    'hunt.rules.4': 'When the last gem is found, the player with the most points wins.',
    'hunt.players': 'Players',
    'hunt.danger': 'Trapdoors',
    'hunt.danger.few': 'Few',
    'hunt.danger.some': 'Some',
    'hunt.danger.many': 'Many',
    'hunt.boardLabel': 'Treasure field',
    'hunt.tileHidden': 'Tile {n}, hidden',
    'hunt.tileGem': 'Tile {n}: a gem worth {value}',
    'hunt.tileTrap': 'Tile {n}: a trapdoor',
    'hunt.pot': 'Pot',
    'hunt.potEmpty': 'Open a tile to find a gem!',
    'hunt.potHint': 'Bank it to keep it — or keep digging.',
    'hunt.odds': '{traps} trapdoors are hiding among {hidden} tiles.',
    'hunt.oddsOne': '1 trapdoor is hiding among {hidden} tiles.',
    'hunt.oddsNone': 'No trapdoors left — keep digging!',
    'hunt.gemsLeft': 'Gems left: {n}',
    'hunt.gemAnn': '{name} found a gem worth {value}!',
    'hunt.trapAnn': 'Oops! {name} opened a trapdoor and lost {lost} points.',
    'hunt.trapNone': 'Oops! {name} opened a trapdoor.',
    'hunt.bankAnn': '{name} banked {amount} points.',
    'hunt.autoBankAnn': '{name} found the last gem and banked {amount} points!',
    'hunt.win': '{name} wins with {n} points!',
    'hunt.winSub': 'What a treasure hunter!',
    'hunt.tie': 'It’s a tie!',
    'hunt.tieSub': '{names} have the same number of points.',
    'hunt.changePlayers': 'Change players',
    'hunt.keys': 'Arrow keys move, Enter opens a tile, B banks.',
  },
  fa: {
    'hunt.title': 'شکار گنج',
    'hunt.tagline': 'بکن. جمع کن. بانک کن!',
    'hunt.rules.1': 'در نوبتت کاشی‌ها را یکی‌یکی باز کن. جواهرها به پات تو می‌روند.',
    'hunt.rules.2': 'اگر دریچهٔ تله را باز کنی پاتت می‌سوزد — و نوبتت تمام می‌شود!',
    'hunt.rules.3': 'هر زمان بانک کنی پاتت ذخیره می‌شود. بعد نوبت بازیکن بعدی است.',
    'hunt.rules.4': 'وقتی آخرین جواهر پیدا شد، کسی که بیشترین امتیاز را دارد برنده است.',
    'hunt.players': 'تعداد بازیکن',
    'hunt.danger': 'دریچهٔ تله',
    'hunt.danger.few': 'کم',
    'hunt.danger.some': 'متوسط',
    'hunt.danger.many': 'زیاد',
    'hunt.boardLabel': 'زمین گنج',
    'hunt.tileHidden': 'کاشی {n}، پنهان',
    'hunt.tileGem': 'کاشی {n}: جواهری با ارزش {value}',
    'hunt.tileTrap': 'کاشی {n}: دریچهٔ تله',
    'hunt.pot': 'پات',
    'hunt.potEmpty': 'یک کاشی را باز کن تا جواهر پیدا کنی!',
    'hunt.potHint': 'بانکش کن تا بماند — یا به کندن ادامه بده.',
    'hunt.odds': '{traps} دریچهٔ تله بین {hidden} کاشی پنهان است.',
    'hunt.oddsOne': '۱ دریچهٔ تله بین {hidden} کاشی پنهان است.',
    'hunt.oddsNone': 'دیگر دریچهٔ تله‌ای نمانده — به کندن ادامه بده!',
    'hunt.gemsLeft': 'جواهرهای باقی‌مانده: {n}',
    'hunt.gemAnn': '{name} جواهری با ارزش {value} پیدا کرد!',
    'hunt.trapAnn': 'وای! {name} دریچهٔ تله را باز کرد و {lost} امتیاز از دست داد.',
    'hunt.trapNone': 'وای! {name} دریچهٔ تله را باز کرد.',
    'hunt.bankAnn': '{name} {amount} امتیاز را بانک کرد.',
    'hunt.autoBankAnn': '{name} آخرین جواهر را پیدا کرد و {amount} امتیاز بانک کرد!',
    'hunt.win': '{name} با {n} امتیاز برنده شد!',
    'hunt.winSub': 'چه شکارچی گنجی!',
    'hunt.tie': 'مساوی شد!',
    'hunt.tieSub': '{names} امتیاز برابر دارند.',
    'hunt.changePlayers': 'تغییر بازیکنان',
    'hunt.keys': 'با کلیدهای جهت‌نما حرکت کن، با Enter کاشی را باز کن و با B بانک کن.',
  },
};

registerStrings(strings);

export default strings;
