import { registerStrings } from '../../shared/i18n/index.jsx';

/** Dots & Boxes text (the lobby card strings live in `casino/strings.js`). */
const strings = {
  en: {
    'dab.title': 'Dots & Boxes',
    'dab.tagline': 'Connect. Close. Collect.',
    'dab.rules.1': 'Take turns drawing one line between two dots.',
    'dab.rules.2': 'Draw the 4th side of a box to win it — and go again!',
    'dab.rules.3': 'If you did not finish a box, it is the next player’s turn.',
    'dab.rules.4': 'When every line is drawn, the player with the most boxes wins.',
    'dab.players': 'Players',
    'dab.size': 'Board size',
    'dab.size.3': 'Small',
    'dab.size.4': 'Medium',
    'dab.size.5': 'Large',
    'dab.size.6': 'Huge',
    'dab.boardLabel': 'Dots and Boxes board',
    'dab.edgeH': 'Horizontal line, row {row}, column {col}',
    'dab.edgeV': 'Vertical line, row {row}, column {col}',
    'dab.drawn': '{label}, drawn by {name}',
    'dab.lineAnn': '{name} drew a line.',
    'dab.boxOne': '{name} completed a box! Go again!',
    'dab.boxMany': '{name} completed {n} boxes! Go again!',
    'dab.boxes': '{n} boxes',
    'dab.win': '{name} wins with {n} boxes!',
    'dab.winSub': 'Great planning!',
    'dab.tie': 'It’s a tie!',
    'dab.tieSub': '{names} have the same number of boxes.',
    'dab.changePlayers': 'Change players',
    'dab.keys': 'Arrow keys move along the lines, Enter draws.',
  },
  fa: {
    'dab.title': 'نقطه و جعبه',
    'dab.tagline': 'وصل کن. ببند. جمع کن.',
    'dab.rules.1': 'نوبتی یک خط بین دو نقطه بکش.',
    'dab.rules.2': 'ضلع چهارم یک جعبه را بکشی، جعبه مال تو می‌شود — و دوباره بازی می‌کنی!',
    'dab.rules.3': 'اگر جعبه‌ای کامل نکردی، نوبت بازیکن بعدی است.',
    'dab.rules.4': 'وقتی همهٔ خط‌ها کشیده شد، کسی که جعبهٔ بیشتری دارد برنده است.',
    'dab.players': 'تعداد بازیکن',
    'dab.size': 'اندازهٔ صفحه',
    'dab.size.3': 'کوچک',
    'dab.size.4': 'متوسط',
    'dab.size.5': 'بزرگ',
    'dab.size.6': 'خیلی بزرگ',
    'dab.boardLabel': 'صفحهٔ نقطه و جعبه',
    'dab.edgeH': 'خط افقی، ردیف {row}، ستون {col}',
    'dab.edgeV': 'خط عمودی، ردیف {row}، ستون {col}',
    'dab.drawn': '{label}، کشیده شده توسط {name}',
    'dab.lineAnn': '{name} یک خط کشید.',
    'dab.boxOne': '{name} یک جعبه را کامل کرد! دوباره بازی کن!',
    'dab.boxMany': '{name} {n} جعبه را کامل کرد! دوباره بازی کن!',
    'dab.boxes': '{n} جعبه',
    'dab.win': '{name} با {n} جعبه برنده شد!',
    'dab.winSub': 'برنامه‌ریزی عالی!',
    'dab.tie': 'مساوی شد!',
    'dab.tieSub': '{names} تعداد جعبهٔ برابر دارند.',
    'dab.changePlayers': 'تغییر بازیکنان',
    'dab.keys': 'با کلیدهای جهت‌نما روی خط‌ها حرکت کن، با Enter خط بکش.',
  },
};

registerStrings(strings);

export default strings;
