import { registerStrings } from '../../shared/i18n/index.jsx';

/** Memory Match text (the lobby card strings live in `casino/strings.js`). */
const strings = {
  en: {
    'mem.title': 'Memory Match',
    'mem.tagline': 'Flip. Remember. Match.',
    'mem.rules.1': 'On your turn, flip two cards.',
    'mem.rules.2': 'If they match, you keep them and go again!',
    'mem.rules.3': 'If not, they flip back — try to remember where they are.',
    'mem.rules.4': 'Whoever finds the most pairs wins.',
    'mem.players': 'Players',
    'mem.size': 'Board size',
    'mem.size.3x4': 'Small',
    'mem.size.4x4': 'Medium',
    'mem.size.4x5': 'Large',
    'mem.size.6x6': 'Huge',
    'mem.boardLabel': 'Memory Match board',
    'mem.cardDown': 'Card {n}, face down',
    'mem.cardUp': 'Card {n}: {symbol}',
    'mem.cardFound': 'Card {n}: {symbol}, found by {name}',
    'mem.symbol': '{color} {shape}',
    'mem.shape.0': 'circle',
    'mem.shape.1': 'square',
    'mem.shape.2': 'triangle',
    'mem.shape.3': 'star',
    'mem.shape.4': 'heart',
    'mem.shape.5': 'diamond',
    'mem.color.0': 'red',
    'mem.color.1': 'blue',
    'mem.color.2': 'green',
    'mem.tries': 'Tries: {n}',
    'mem.matchAnn': '{name} found a pair!',
    'mem.missAnn': 'No match. Next turn.',
    'mem.win': '{name} wins with {n} pairs!',
    'mem.winSub': 'Great memory!',
    'mem.tie': 'It’s a tie!',
    'mem.tieSub': '{names} found the same number of pairs.',
    'mem.solo': 'You found every pair!',
    'mem.soloSub': 'It took you {n} tries.',
    'mem.changePlayers': 'Change players',
    'mem.keys': 'Arrow keys move between cards, Enter flips.',
  },
  fa: {
    'mem.title': 'بازی حافظه',
    'mem.tagline': 'برگردان. یادت بماند. جفت کن.',
    'mem.rules.1': 'در نوبتت دو کارت را برگردان.',
    'mem.rules.2': 'اگر یکسان بودند، آن‌ها مال تو می‌شوند و دوباره بازی می‌کنی!',
    'mem.rules.3': 'اگر نه، دوباره برمی‌گردند — سعی کن جای آن‌ها را به خاطر بسپاری.',
    'mem.rules.4': 'هر کس جفت‌های بیشتری پیدا کند برنده است.',
    'mem.players': 'تعداد بازیکن',
    'mem.size': 'اندازهٔ صفحه',
    'mem.size.3x4': 'کوچک',
    'mem.size.4x4': 'متوسط',
    'mem.size.4x5': 'بزرگ',
    'mem.size.6x6': 'خیلی بزرگ',
    'mem.boardLabel': 'صفحهٔ بازی حافظه',
    'mem.cardDown': 'کارت {n}، پشت‌رو',
    'mem.cardUp': 'کارت {n}: {symbol}',
    'mem.cardFound': 'کارت {n}: {symbol}، پیدا شده توسط {name}',
    'mem.symbol': '{shape} {color}',
    'mem.shape.0': 'دایره',
    'mem.shape.1': 'مربع',
    'mem.shape.2': 'مثلث',
    'mem.shape.3': 'ستاره',
    'mem.shape.4': 'قلب',
    'mem.shape.5': 'لوزی',
    'mem.color.0': 'قرمز',
    'mem.color.1': 'آبی',
    'mem.color.2': 'سبز',
    'mem.tries': 'تلاش‌ها: {n}',
    'mem.matchAnn': '{name} یک جفت پیدا کرد!',
    'mem.missAnn': 'یکسان نبودند. نوبت بعدی.',
    'mem.win': '{name} با {n} جفت برنده شد!',
    'mem.winSub': 'حافظهٔ عالی!',
    'mem.tie': 'مساوی شد!',
    'mem.tieSub': '{names} به تعداد برابر جفت پیدا کردند.',
    'mem.solo': 'همهٔ جفت‌ها را پیدا کردی!',
    'mem.soloSub': 'با {n} تلاش.',
    'mem.changePlayers': 'تغییر بازیکنان',
    'mem.keys': 'با کلیدهای جهت‌نما بین کارت‌ها حرکت کن و با Enter برگردان.',
  },
};

registerStrings(strings);

export default strings;
